// Generated by gencpp from file pd_controller/JointControlReference.msg
// DO NOT EDIT!


#ifndef PD_CONTROLLER_MESSAGE_JOINTCONTROLREFERENCE_H
#define PD_CONTROLLER_MESSAGE_JOINTCONTROLREFERENCE_H

#include <ros/service_traits.h>


#include <pd_controller/JointControlReferenceRequest.h>
#include <pd_controller/JointControlReferenceResponse.h>


namespace pd_controller
{

struct JointControlReference
{

typedef JointControlReferenceRequest Request;
typedef JointControlReferenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointControlReference
} // namespace pd_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pd_controller::JointControlReference > {
  static const char* value()
  {
    return "cabb4d8365c1affb33eb07e1622932fc";
  }

  static const char* value(const ::pd_controller::JointControlReference&) { return value(); }
};

template<>
struct DataType< ::pd_controller::JointControlReference > {
  static const char* value()
  {
    return "pd_controller/JointControlReference";
  }

  static const char* value(const ::pd_controller::JointControlReference&) { return value(); }
};


// service_traits::MD5Sum< ::pd_controller::JointControlReferenceRequest> should match
// service_traits::MD5Sum< ::pd_controller::JointControlReference >
template<>
struct MD5Sum< ::pd_controller::JointControlReferenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pd_controller::JointControlReference >::value();
  }
  static const char* value(const ::pd_controller::JointControlReferenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pd_controller::JointControlReferenceRequest> should match
// service_traits::DataType< ::pd_controller::JointControlReference >
template<>
struct DataType< ::pd_controller::JointControlReferenceRequest>
{
  static const char* value()
  {
    return DataType< ::pd_controller::JointControlReference >::value();
  }
  static const char* value(const ::pd_controller::JointControlReferenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pd_controller::JointControlReferenceResponse> should match
// service_traits::MD5Sum< ::pd_controller::JointControlReference >
template<>
struct MD5Sum< ::pd_controller::JointControlReferenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pd_controller::JointControlReference >::value();
  }
  static const char* value(const ::pd_controller::JointControlReferenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pd_controller::JointControlReferenceResponse> should match
// service_traits::DataType< ::pd_controller::JointControlReference >
template<>
struct DataType< ::pd_controller::JointControlReferenceResponse>
{
  static const char* value()
  {
    return DataType< ::pd_controller::JointControlReference >::value();
  }
  static const char* value(const ::pd_controller::JointControlReferenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PD_CONTROLLER_MESSAGE_JOINTCONTROLREFERENCE_H
